"""Agent monitoring and improvement API router.

Endpoints:
    GET /api/v1/agents/status — Pipeline status and agent outputs from last run
    GET /api/v1/agents/improvements — List recent improvement records
    POST /api/v1/agents/improvements/apply — Apply an improvement suggestion
    GET /api/v1/agents/improvements/metrics — Get aggregate metrics summary
"""

from __future__ import annotations

from typing import Any

from fastapi import APIRouter, HTTPException

from agents.improvement import get_improvement_engine
from backend.routers.analysis import get_last_state

router = APIRouter(prefix="/api/v1/agents", tags=["agents"])


@router.get("/status")
async def agent_status() -> dict[str, Any]:
    """Get pipeline execution status from the last run.

    Returns current_node, completed/failed/skipped agent lists,
    model chain used for each agent, and degradation status.
    """
    state = get_last_state()
    if state is None:
        return {
            "pipeline_status": {
                "current_node": "",
                "completed_nodes": [],
                "failed_nodes": [],
                "skipped_nodes": [],
            },
            "model_chain_used": {},
            "degraded": False,
            "total_latency_ms": 0,
            "has_run": False,
        }

    state_dict = state.model_dump() if hasattr(state, "model_dump") else getattr(state, "dict", lambda: {})()
    if not state_dict and hasattr(state, "__dict__"):
        state_dict = {k: v for k, v in state.__dict__.items() if not k.startswith("_")}
        # Handle Pydantic models inside state
        for k, v in state_dict.items():
            if hasattr(v, "model_dump"):
                state_dict[k] = v.model_dump()

    return {
        **state_dict,
        "has_run": True,
    }


@router.get("/improvements")
async def list_improvements(limit: int = 20) -> list[dict[str, Any]]:
    """List recent improvement records generated by the StrategyImprovementEngine.

    Args:
        limit: Maximum number of records to return (default 20, max 100).
    """
    engine = get_improvement_engine()
    capped = min(limit, 100)
    return engine.get_recent_improvements(limit=capped)


@router.post("/improvements/apply")
async def apply_improvement(body: dict[str, Any]) -> dict[str, Any]:
    """Mark an improvement suggestion as applied.

    Request body::

        {"record_id": "imp_1234567890"}
    """
    record_id = body.get("record_id", "")
    if not record_id:
        raise HTTPException(status_code=400, detail="record_id is required")

    engine = get_improvement_engine()
    success = engine.apply_improvement(record_id)
    if not success:
        raise HTTPException(
            status_code=404,
            detail=f"Improvement record '{record_id}' not found",
        )
    return {"success": True, "record_id": record_id}


@router.get("/improvements/metrics")
async def improvement_metrics() -> dict[str, float]:
    """Get aggregate improvement metrics summary.

    Returns avg_confidence_accuracy, win_rate, error_rate, total_runs.
    """
    engine = get_improvement_engine()
    return engine.get_metrics_summary()
