"""Strategy Improvement Engine — cross-session performance analysis.

Reads reflection output across recent pipeline runs, detects performance
degradation, and generates parameter tuning suggestions.

This runs after the Memory Agent in the pipeline, analyzing trends
across multiple runs rather than just a single session.
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import Any


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

WIN_RATE_DECLINE_THRESHOLD: float = 0.15
"""Win rate decline (over 10 runs) that triggers a degradation alert."""

CONFIDENCE_ACCURACY_DECLINE_THRESHOLD: float = 10.0
"""Confidence accuracy decline (in percentage points) that triggers an alert."""

MIN_RUNS_FOR_ANALYSIS: int = 5
"""Minimum number of historical runs needed for trend analysis."""

IMPROVEMENT_MAX_HISTORY: int = 100
"""Maximum number of improvement records to retain in memory."""


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------


@dataclass
class ImprovementRecord:
    """A single improvement suggestion generated by the engine."""

    id: str
    timestamp: str
    category: str  # "parameter_tuning", "agent_config", "risk_calibration", "data_quality"
    description: str
    severity: str  # "low", "medium", "high", "critical"
    metric_before: float | None = None
    metric_after: float | None = None
    applied: bool = False
    rationale: str = ""
    suggested_params: dict[str, Any] = field(default_factory=dict)


@dataclass
class ImprovementRunResult:
    """Result of a single improvement analysis run."""

    records: list[ImprovementRecord]
    metrics: dict[str, float]
    warnings: list[str]
    run_timestamp: str


# ---------------------------------------------------------------------------
# In-memory store (replaced with DB storage in production)
# ---------------------------------------------------------------------------

_improvement_history: list[ImprovementRecord] = []
_reflection_history: list[dict[str, Any]] = []


def _reset_history() -> None:
    """Clear all in-memory history (for testing)."""
    global _improvement_history, _reflection_history
    _improvement_history = []
    _reflection_history = []


# ---------------------------------------------------------------------------
# Strategy Improvement Engine
# ---------------------------------------------------------------------------


class StrategyImprovementEngine:
    """Cross-session strategy improvement analyzer.

    Examines reflection outputs across multiple runs to detect:
    - Declining win rate or confidence accuracy
    - Increasing error rates
    - Pattern of risk-approval changes
    - Agent-specific reliability degradation
    """

    def __init__(self, history_size: int = IMPROVEMENT_MAX_HISTORY) -> None:
        self.history_size = history_size

    def analyze(self, reflection_output: dict[str, Any]) -> ImprovementRunResult:
        """Run improvement analysis on the latest reflection output.

        Args:
            reflection_output: The output dict from a ReflectionAgent run,
                               containing evaluation, confidence_accuracy,
                               improvement_suggestions, and knowledge_updates.

        Returns:
            ImprovementRunResult with any new improvement records, metrics,
            and warnings.
        """
        global _reflection_history, _improvement_history

        # Store reflection output
        _reflection_history.append({
            **reflection_output,
            "_timestamp": datetime.now(UTC).isoformat(),
        })
        # Trim history
        if len(_reflection_history) > self.history_size:
            _reflection_history = _reflection_history[-self.history_size:]

        warnings: list[str] = []
        records: list[ImprovementRecord] = []

        # Compute aggregate metrics
        metrics = self._compute_metrics()

        # Check if we have enough data for trend analysis
        if len(_reflection_history) < MIN_RUNS_FOR_ANALYSIS:
            warnings.append(
                f"Only {len(_reflection_history)}/{MIN_RUNS_FOR_ANALYSIS} runs collected "
                f"for trend analysis"
            )
            return ImprovementRunResult(records=records, metrics=metrics, warnings=warnings, run_timestamp=datetime.now(UTC).isoformat())

        # Trend checks
        records.extend(self._check_win_rate_trend(metrics))
        records.extend(self._check_confidence_accuracy_trend(metrics))
        records.extend(self._check_error_rate(reflection_output))
        records.extend(self._check_suggestion_overlap(reflection_output))

        # Trim improvement history
        if len(_improvement_history) > self.history_size:
            _improvement_history = _improvement_history[-self.history_size:]

        return ImprovementRunResult(
            records=records,
            metrics=metrics,
            warnings=warnings,
            run_timestamp=datetime.now(UTC).isoformat(),
        )

    def _compute_metrics(self) -> dict[str, float]:
        """Compute aggregate metrics across recent reflection history."""
        recent = _reflection_history[-MIN_RUNS_FOR_ANALYSIS:] if len(_reflection_history) >= MIN_RUNS_FOR_ANALYSIS else _reflection_history
        total = len(recent)
        if total == 0:
            return {
                "avg_confidence_accuracy": 0.0,
                "win_rate": 0.0,
                "error_rate": 0.0,
                "total_runs": 0.0,
            }

        # Average confidence accuracy
        accuracies = [r.get("confidence_accuracy", 0) for r in recent]
        avg_accuracy = sum(accuracies) / len(accuracies) if accuracies else 0.0

        # Win rate: how many evaluations mention "executed" favorably
        executed_count = sum(
            1 for r in recent
            if "Trade executed" in r.get("evaluation", "")
        )
        win_rate = executed_count / total if total > 0 else 0.0

        # Error rate from suggestion overlap
        suggestions_with_errors = sum(
            1 for r in recent
            if any("error" in s.lower() for s in r.get("improvement_suggestions", []))
        )
        error_rate = suggestions_with_errors / total if total > 0 else 0.0

        return {
            "avg_confidence_accuracy": round(avg_accuracy, 2),
            "win_rate": round(win_rate * 100, 2),
            "error_rate": round(error_rate * 100, 2),
            "total_runs": float(total),
        }

    def _check_win_rate_trend(self, metrics: dict[str, float]) -> list[ImprovementRecord]:
        """Check if win rate has declined significantly."""
        records: list[ImprovementRecord] = []

        # Compare recent half vs older half of the window
        recent = _reflection_history[-MIN_RUNS_FOR_ANALYSIS:] if len(_reflection_history) >= MIN_RUNS_FOR_ANALYSIS * 2 else []
        if len(recent) < MIN_RUNS_FOR_ANALYSIS:
            return records

        mid = len(recent) // 2
        older_half = recent[:mid]
        newer_half = recent[mid:]

        older_rate = sum(
            1 for r in older_half if "Trade executed" in r.get("evaluation", "")
        ) / len(older_half) if older_half else 0

        newer_rate = sum(
            1 for r in newer_half if "Trade executed" in r.get("evaluation", "")
        ) / len(newer_half) if newer_half else 0

        decline = older_rate - newer_rate
        if decline > WIN_RATE_DECLINE_THRESHOLD:
            record = ImprovementRecord(
                id=_next_id(),
                timestamp=datetime.now(UTC).isoformat(),
                category="risk_calibration",
                severity="high",
                description=f"Win rate declined by {decline:.1%} over recent runs",
                metric_before=round(older_rate * 100, 2),
                metric_after=round(newer_rate * 100, 2),
                rationale=f"Execution rate dropped from {older_rate:.1%} to {newer_rate:.1%}. "
                          f"Consider reviewing risk thresholds and consensus confidence criteria.",
                suggested_params={"max_drawdown_pct": 15.0, "min_consensus_confidence": 75.0},
            )
            records.append(record)
            _improvement_history.append(record)

        return records

    def _check_confidence_accuracy_trend(self, metrics: dict[str, float]) -> list[ImprovementRecord]:
        """Check if confidence accuracy has declined."""
        records: list[ImprovementRecord] = []

        if len(_reflection_history) < MIN_RUNS_FOR_ANALYSIS * 2:
            return records

        mid = len(_reflection_history) // 2
        older = [r.get("confidence_accuracy", 0) for r in _reflection_history[:mid]]
        newer = [r.get("confidence_accuracy", 0) for r in _reflection_history[mid:]]

        older_avg = sum(older) / len(older) if older else 0
        newer_avg = sum(newer) / len(newer) if newer else 0
        decline = older_avg - newer_avg

        if decline > CONFIDENCE_ACCURACY_DECLINE_THRESHOLD:
            record = ImprovementRecord(
                id=_next_id(),
                timestamp=datetime.now(UTC).isoformat(),
                category="agent_config",
                severity="high",
                description=f"Confidence accuracy declined by {decline:.1f} points",
                metric_before=round(older_avg, 2),
                metric_after=round(newer_avg, 2),
                rationale=f"Average confidence accuracy dropped from {older_avg:.1f} to {newer_avg:.1f}. "
                          f"Consider recalibrating Market Analyst and Quant confidence thresholds.",
                suggested_params={"market_analyst_confidence_threshold": 85.0},
            )
            records.append(record)
            _improvement_history.append(record)

        return records

    def _check_error_rate(self, reflection_output: dict[str, Any]) -> list[ImprovementRecord]:
        """Check for rising error rates in suggestions."""
        records: list[ImprovementRecord] = []

        suggestions = reflection_output.get("improvement_suggestions", [])
        error_suggestions = [s for s in suggestions if "error" in s.lower()]

        if error_suggestions:
            # Check if errors are persistent across recent runs
            recent = _reflection_history[-3:] if len(_reflection_history) >= 3 else _reflection_history
            persistent_errors = all(
                any("error" in s.lower() for s in r.get("improvement_suggestions", []))
                for r in recent
            )
            if persistent_errors:
                record = ImprovementRecord(
                    id=_next_id(),
                    timestamp=datetime.now(UTC).isoformat(),
                    category="agent_config",
                    severity="critical",
                    description="Persistent errors detected across multiple runs",
                    rationale="Errors appear in improvement suggestions across recent runs. "
                              "Check model availability, API keys, and fallback chain health.",
                    suggested_params={"circuit_breaker_threshold": 2},
                )
                records.append(record)
                _improvement_history.append(record)

        return records

    def _check_suggestion_overlap(self, reflection_output: dict[str, Any]) -> list[ImprovementRecord]:
        """Check if the same improvement suggestions keep appearing without resolution."""
        records: list[ImprovementRecord] = []

        current_suggestions = set(
            s.lower().strip() for s in reflection_output.get("improvement_suggestions", [])
        )
        if not current_suggestions:
            return records

        # Compare with recent past suggestions
        past_suggestions: list[set[str]] = []
        for r in _reflection_history[-5:-1]:  # last 4 runs (excluding current)
            past_suggestions.append(set(
                s.lower().strip() for s in r.get("improvement_suggestions", [])
            ))

        repeated = current_suggestions
        for ps in past_suggestions:
            repeated = repeated & ps

        if repeated:
            record = ImprovementRecord(
                id=_next_id(),
                timestamp=datetime.now(UTC).isoformat(),
                category="parameter_tuning",
                severity="medium",
                description=f"Repeated suggestions: {', '.join(list(repeated)[:3])}",
                rationale="Same improvement suggestions recurring across runs without resolution. "
                          "Consider addressing the root cause or adjusting pipeline configuration.",
            )
            records.append(record)
            _improvement_history.append(record)

        return records

    # ── Query methods ──────────────────────────────────────────────

    def get_recent_improvements(self, limit: int = 20) -> list[dict[str, Any]]:
        """Get recent improvement records."""
        recent = _improvement_history[-limit:] if _improvement_history else []
        return [
            {
                "id": r.id,
                "timestamp": r.timestamp,
                "category": r.category,
                "description": r.description,
                "severity": r.severity,
                "metric_before": r.metric_before,
                "metric_after": r.metric_after,
                "applied": r.applied,
                "rationale": r.rationale,
            }
            for r in recent
        ]

    def get_metrics_summary(self) -> dict[str, float]:
        """Get current aggregate metrics summary."""
        return self._compute_metrics()

    def apply_improvement(self, record_id: str) -> bool:
        """Mark an improvement record as applied."""
        for record in _improvement_history:
            if record.id == record_id:
                record.applied = True
                return True
        return False


# Global singleton
_engine = StrategyImprovementEngine()


def get_improvement_engine() -> StrategyImprovementEngine:
    """Get the global StrategyImprovementEngine singleton."""
    return _engine


def _next_id() -> str:
    """Generate a unique improvement record ID."""
    ts = int(time.time() * 1000)
    return f"imp_{ts}"


def reset_engine() -> None:
    """Reset the engine and all history (for testing)."""
    global _engine
    _reset_history()
    _engine = StrategyImprovementEngine()
